### ISSUE TITLE
v3.70 stalls and disconnects

### ISSUE THREAD

**Issue by tpoppins** [RZulu54/ChessBrainVB#4]
In an ongoing 40/40 test ChessBrainVB 3.70 64-bit lost practically every game with Black due to stalled connections or disconnects. Out of 30 participants, ranging from Xiphos and Arasan down to GreKo and Marvin, this is the only engine to have any problems in this test.

One example out of 19:

PGN 
```
[Event "?"]
[Site "?"]
[Date "2018.11.12"]
[Round "?"]
[White "Demolito 2018-10-29 64-bit"]
[Black "ChessBrainVB 3.70"]
[Result "1-0"]
[ECO "A40"]
[GameDuration "00:25:20"]
[GameEndTime "2018-11-12T22:58:10.354 Eastern Standard Time"]
[GameStartTime "2018-11-12T22:32:49.809 Eastern Standard Time"]
[Opening "Queen's pawn"]
[PlyCount "25"]
[Termination "stalled connection"]
[TimeControl "40/1200"]
[Variation "Franco-Indian (Keres) defense"]

1. d4 {book} e6 {book} 2. c4 {book} Bb4+ {book} 3. Nd2 {book} c5 {book}
4. e3 {+0.28/20 31s} cxd4 {-0.51/14 6.1s} 5. exd4 {+0.24/21 30s}
Nf6 {-0.28/18 8.6s} 6. Nf3 {+0.24/22 29s} Be7 {-0.17/16 4.9s}
7. Bd3 {+0.36/22 29s} b6 {-0.29/19 15s} 8. O-O {+0.34/21 30s}
O-O {-0.15/15 3.5s} 9. a3 {+0.28/21 29s} d5 {-0.15/18 9.3s}
10. b4 {+0.30/21 30s} dxc4 {+0.16/16 3.9s} 11. Nxc4 {+0.40/21 30s}
Bb7 {0.00/17 9.6s} 12. Bb2 {+0.25/19 31s} Nbd7 {+0.14/14 4.3s}
13. Re1 {+0.36/20 31s, Black's connection stalls} 1-0

```

WER report

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	ChessBrainVB-370.exe
  Application Version:	3.7.0.0
  Application Timestamp:	5ba0025d
  Fault Module Name:	ChessBrainVB-370.exe
  Fault Module Version:	3.7.0.0
  Fault Module Timestamp:	5ba0025d
  Exception Code:	c0000005
  Exception Offset:	0001f6a8
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	9c2a
  Additional Information 2:	9c2af5251156b3873c9ee911e8dff81d
  Additional Information 3:	d7e5
  Additional Information 4:	d7e5827e2d088af9440ebf3208077cab
  
```

Debug log
[ChessBrainVB-370-stall-log.txt](https://github.com/RZulu54/ChessBrainVB/files/2574717/ChessBrainVB-370-stall-log.txt)

Dual Xeon E5-2690v2 @3 GHz, 20 cores, HT off, 32 GB RAM
Win 7 x64 Pro SP1
Cute Chess GUI  20181029 64-bit dev build
512 MB hash, 1 thread
concurrency=18

Tirsa@CCRL

**Comment by tpoppins** [comment]
An example of a disconnect

PGN


```
[Event "?"]
[Site "?"]
[Date "2018.11.12"]
[Round "?"]
[White "Demolito 2018-10-29 64-bit"]
[Black "ChessBrainVB 3.70"]
[Result "1-0"]
[ECO "C62"]
[GameDuration "00:07:34"]
[GameEndTime "2018-11-12T23:30:31.277 Eastern Standard Time"]
[GameStartTime "2018-11-12T23:22:57.017 Eastern Standard Time"]
[Opening "Ruy Lopez"]
[PlyCount "31"]
[Termination "abandoned"]
[TimeControl "40/1260"]
[Variation "Old Steinitz defense"]

1. e4 {book} e5 {book} 2. Nf3 {book} Nc6 {book} 3. Bb5 {book} d6 {book}
4. d4 {book} Bd7 {book} 5. Nc3 {book} exd4 {book} 6. Nxd4 {book} g6 {book}
7. Be3 {+0.47/20 35s} Bg7 {+0.11/15 6.7s} 8. Qd2 {+0.45/20 35s}
Nf6 {-0.26/18 17s} 9. f3 {+0.44/20 34s} O-O {-0.63/16 10s}
10. Be2 {+0.43/20 35s} a6 {-0.29/15 3.4s} 11. O-O {+0.43/20 35s}
Re8 {-0.18/15 3.5s} 12. a4 {+0.37/20 34s} Nb4 {-0.47/16 20s}
13. Nb3 {+0.42/20 36s} Qe7 {-0.29/16 17s} 14. Rfd1 {+0.31/18 39s}
Be6 {-0.01/16 19s} 15. Bf2 {+0.15/19 35s} Nh5 {+0.21/15 3.8s}
16. Nd4 {+0.28/19 36s, Black disconnects} 1-0

```


WER report 

```
Version=1
EventType=APPCRASH
EventTime=131865570309778050
ReportType=2
Consent=1
ReportIdentifier=da0f3983-e6fc-11e8-ac1d-002713cab278
IntegratorReportIdentifier=da0f3982-e6fc-11e8-ac1d-002713cab278
WOW64=1
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=ChessBrainVB-370.exe
Sig[1].Name=Application Version
Sig[1].Value=3.7.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5ba0025d
Sig[3].Name=Fault Module Name
Sig[3].Value=ChessBrainVB-370.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=3.7.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5ba0025d
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0001f6a8
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=9c2a
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=9c2af5251156b3873c9ee911e8dff81d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=d7e5
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=d7e5827e2d088af9440ebf3208077cab
UI[2]=C:\Program Files\ChessBase\Engines.x64\ChessBrainVB-370.exe
UI[3]=VB6 chess engine has stopped working
UI[4]=Windows can check online for a solution to the problem the next time you go online.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\ChessBase\Engines.x64\ChessBrainVB-370.exe
LoadedModule[1]=C:\Windows\SysWOW64\ntdll.dll
LoadedModule[2]=C:\Windows\syswow64\kernel32.dll
LoadedModule[3]=C:\Windows\syswow64\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\MSVBVM60.DLL
LoadedModule[5]=C:\Windows\syswow64\USER32.dll
LoadedModule[6]=C:\Windows\syswow64\GDI32.dll
LoadedModule[7]=C:\Windows\syswow64\LPK.dll
LoadedModule[8]=C:\Windows\syswow64\USP10.dll
LoadedModule[9]=C:\Windows\syswow64\msvcrt.dll
LoadedModule[10]=C:\Windows\syswow64\ADVAPI32.dll
LoadedModule[11]=C:\Windows\SysWOW64\sechost.dll
LoadedModule[12]=C:\Windows\syswow64\RPCRT4.dll
LoadedModule[13]=C:\Windows\syswow64\SspiCli.dll
LoadedModule[14]=C:\Windows\syswow64\CRYPTBASE.dll
LoadedModule[15]=C:\Windows\syswow64\ole32.dll
LoadedModule[16]=C:\Windows\syswow64\OLEAUT32.dll
LoadedModule[17]=C:\Windows\system32\IMM32.DLL
LoadedModule[18]=C:\Windows\syswow64\MSCTF.dll
LoadedModule[19]=C:\Windows\system32\uxtheme.dll
LoadedModule[20]=C:\Program Files\NVIDIA Corporation\nView\nview.dll
LoadedModule[21]=C:\Windows\syswow64\SHLWAPI.dll
LoadedModule[22]=C:\Windows\syswow64\SHELL32.dll
LoadedModule[23]=C:\Windows\syswow64\PSAPI.DLL
LoadedModule[24]=C:\Windows\system32\VERSION.dll
LoadedModule[25]=C:\Windows\system32\WTSAPI32.dll
LoadedModule[26]=C:\Windows\system32\MSIMG32.dll
LoadedModule[27]=C:\Windows\system32\WINMM.dll
LoadedModule[28]=C:\Windows\system32\POWRPROF.dll
LoadedModule[29]=C:\Windows\syswow64\SETUPAPI.dll
LoadedModule[30]=C:\Windows\syswow64\CFGMGR32.dll
LoadedModule[31]=C:\Windows\syswow64\DEVOBJ.dll
LoadedModule[32]=C:\Windows\system32\ntmarta.dll
LoadedModule[33]=C:\Windows\syswow64\WLDAP32.dll
LoadedModule[34]=C:\Program Files\NVIDIA Corporation\nView\NVWRSENU.dll
LoadedModule[35]=C:\Windows\system32\SXS.DLL
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=VB6 chess engine
AppPath=C:\Program Files\ChessBase\Engines.x64\ChessBrainVB-370.exe

```

Debug log
[ChessBrainVB-370-disconnect-log.txt](https://github.com/RZulu54/ChessBrainVB/files/2574800/ChessBrainVB-370-disconnect-log.txt)


This is on a dual Xeon X5670 @2.93 GHz, 12 cores, HT off, 48 GB RAM, concurrency=8; everything else is same as the other system above.

**Comment by RZulu54** [comment]
Hello,
I never had problems with ARENA GUI, but for CuteChess client there are problems with long UCI string sent very fast.The engine language VisualBasic has to use some special polling logic for the client interface which is different to C language.
Please setup the engine as Winboard  which uses short commands.
For the TCEC CUteChess client the attached file Chessbrainvb.ini was used. I already changed the TCEC settings to THREADS=1 and HASHSIZE = 512, but you may change them. Please copy the file to the ChessBrainVB.exe directory.
Thanks you for testing,Roger Zuehlsdorf


    Am Dienstag, 13. November 2018, 07:06:32 MEZ hat tpoppins <notifications@github.com> Folgendes geschrieben:  
 
 
An example of a disconnect

PGN
[Event "?"]
[Site "?"]
[Date "2018.11.12"]
[Round "?"]
[White "Demolito 2018-10-29 64-bit"]
[Black "ChessBrainVB 3.70"]
[Result "1-0"]
[ECO "C62"]
[GameDuration "00:07:34"]
[GameEndTime "2018-11-12T23:30:31.277 Eastern Standard Time"]
[GameStartTime "2018-11-12T23:22:57.017 Eastern Standard Time"]
[Opening "Ruy Lopez"]
[PlyCount "31"]
[Termination "abandoned"]
[TimeControl "40/1260"]
[Variation "Old Steinitz defense"]

1. e4 {book} e5 {book} 2. Nf3 {book} Nc6 {book} 3. Bb5 {book} d6 {book}
4. d4 {book} Bd7 {book} 5. Nc3 {book} exd4 {book} 6. Nxd4 {book} g6 {book}
7. Be3 {+0.47/20 35s} Bg7 {+0.11/15 6.7s} 8. Qd2 {+0.45/20 35s}
Nf6 {-0.26/18 17s} 9. f3 {+0.44/20 34s} O-O {-0.63/16 10s}
10. Be2 {+0.43/20 35s} a6 {-0.29/15 3.4s} 11. O-O {+0.43/20 35s}
Re8 {-0.18/15 3.5s} 12. a4 {+0.37/20 34s} Nb4 {-0.47/16 20s}
13. Nb3 {+0.42/20 36s} Qe7 {-0.29/16 17s} 14. Rfd1 {+0.31/18 39s}
Be6 {-0.01/16 19s} 15. Bf2 {+0.15/19 35s} Nh5 {+0.21/15 3.8s}
16. Nd4 {+0.28/19 36s, Black disconnects} 1-0


WER report
Version=1
EventType=APPCRASH
EventTime=131865570309778050
ReportType=2
Consent=1
ReportIdentifier=da0f3983-e6fc-11e8-ac1d-002713cab278
IntegratorReportIdentifier=da0f3982-e6fc-11e8-ac1d-002713cab278
WOW64=1
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=ChessBrainVB-370.exe
Sig[1].Name=Application Version
Sig[1].Value=3.7.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5ba0025d
Sig[3].Name=Fault Module Name
Sig[3].Value=ChessBrainVB-370.exe
Sig[4].Name=Fault Module Version
Sig[4].Value=3.7.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=5ba0025d
Sig[6].Name=Exception Code
Sig[6].Value=c0000005
Sig[7].Name=Exception Offset
Sig[7].Value=0001f6a8
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.1.7601.2.1.0.256.48
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=9c2a
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=9c2af5251156b3873c9ee911e8dff81d
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=d7e5
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=d7e5827e2d088af9440ebf3208077cab
UI[2]=C:\Program Files\ChessBase\Engines.x64\ChessBrainVB-370.exe
UI[3]=VB6 chess engine has stopped working
UI[4]=Windows can check online for a solution to the problem the next time you go online.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files\ChessBase\Engines.x64\ChessBrainVB-370.exe
LoadedModule[1]=C:\Windows\SysWOW64\ntdll.dll
LoadedModule[2]=C:\Windows\syswow64\kernel32.dll
LoadedModule[3]=C:\Windows\syswow64\KERNELBASE.dll
LoadedModule[4]=C:\Windows\system32\MSVBVM60.DLL
LoadedModule[5]=C:\Windows\syswow64\USER32.dll
LoadedModule[6]=C:\Windows\syswow64\GDI32.dll
LoadedModule[7]=C:\Windows\syswow64\LPK.dll
LoadedModule[8]=C:\Windows\syswow64\USP10.dll
LoadedModule[9]=C:\Windows\syswow64\msvcrt.dll
LoadedModule[10]=C:\Windows\syswow64\ADVAPI32.dll
LoadedModule[11]=C:\Windows\SysWOW64\sechost.dll
LoadedModule[12]=C:\Windows\syswow64\RPCRT4.dll
LoadedModule[13]=C:\Windows\syswow64\SspiCli.dll
LoadedModule[14]=C:\Windows\syswow64\CRYPTBASE.dll
LoadedModule[15]=C:\Windows\syswow64\ole32.dll
LoadedModule[16]=C:\Windows\syswow64\OLEAUT32.dll
LoadedModule[17]=C:\Windows\system32\IMM32.DLL
LoadedModule[18]=C:\Windows\syswow64\MSCTF.dll
LoadedModule[19]=C:\Windows\system32\uxtheme.dll
LoadedModule[20]=C:\Program Files\NVIDIA Corporation\nView\nview.dll
LoadedModule[21]=C:\Windows\syswow64\SHLWAPI.dll
LoadedModule[22]=C:\Windows\syswow64\SHELL32.dll
LoadedModule[23]=C:\Windows\syswow64\PSAPI.DLL
LoadedModule[24]=C:\Windows\system32\VERSION.dll
LoadedModule[25]=C:\Windows\system32\WTSAPI32.dll
LoadedModule[26]=C:\Windows\system32\MSIMG32.dll
LoadedModule[27]=C:\Windows\system32\WINMM.dll
LoadedModule[28]=C:\Windows\system32\POWRPROF.dll
LoadedModule[29]=C:\Windows\syswow64\SETUPAPI.dll
LoadedModule[30]=C:\Windows\syswow64\CFGMGR32.dll
LoadedModule[31]=C:\Windows\syswow64\DEVOBJ.dll
LoadedModule[32]=C:\Windows\system32\ntmarta.dll
LoadedModule[33]=C:\Windows\syswow64\WLDAP32.dll
LoadedModule[34]=C:\Program Files\NVIDIA Corporation\nView\NVWRSENU.dll
LoadedModule[35]=C:\Windows\system32\SXS.DLL
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=VB6 chess engine
AppPath=C:\Program Files\ChessBase\Engines.x64\ChessBrainVB-370.exe


Debug log
ChessBrainVB-370-disconnect-log.txt

This is on a dual Xeon X5670 @2.93 GHz, 12 cores, HT off, 48 GB RAM, concurrency=8; everything else is same as the other system above.

**Comment by tpoppins** [comment]
Yes, seems to run fine in Winboard mode. In fact I had v3.68 set to use it all along, wonder what made me switch for the new version.

UCI mode should be disabled until fixed. At the moment it's hardly usable.

**Comment by tpoppins** [comment]
Still crashes, even in Winboard mode, on the E5-2690v2. Same exception error code and address. 

Currently running a match between v3.68 and v3.70 with concurrency=2, they crash alternately. Six games out of 12 so far, 50% fail rate.

**Comment by RZulu54** [comment]
Hmm, I have never seen this kind of crash and have no idea what may be the problem.May be CPU related, WindowsOS version, access rights to files...
Sorry,Roger

    Am Dienstag, 13. November 2018, 17:32:42 MEZ hat tpoppins <notifications@github.com> Folgendes geschrieben:  
 
 
Still crashes, even in Winboard mode, on the E5-2690v2. Same exception error code and address.

Currently running a match between v3.68 and v3.70 with concurrency=2, they crash alternately. Six games out of 12 so far, 50% fail rate.

**Comment by tpoppins** [comment]
You could try compiling a debug build with asserts enabled and I would test it; doesn't VB offer some sort of debugging? Code c0000005 is an access violation, surely that could be a pointer in the right direction?

**Comment by RZulu54** [comment]
Hello,
VB6 does not support assert in the compiled EXE, debugging only in the IDE.
Looking at the log It seems that the program tries to init tablebases. 
Please make check that tablebases are disabled in CHECCBRAINVB.INI:
EGTB_ENABLED=0 
Tablebases are not working properly, they are using a DOS call to Fathom.exe.
Other problem may be with hash tables. I'm used a mapped memory file which needs continous free memeory blocks.Please try to reduce the hash size. You can do this directly  in the CHESSBRAINVB.INI
 HASHSIZE_IGNORE_GUI=1
HASHSIZE=128

Regards,Roger

    Am Mittwoch, 14. November 2018, 12:31:11 MEZ hat tpoppins <notifications@github.com> Folgendes geschrieben:  
 
 
You could try compiling a debug build with asserts enabled and I would test it; doesn't VB offer some sort of debugging? Code c0000005 is an access violation, surely that could be a pointer in the right direction?

**Comment by tpoppins** [comment]
OK, I will try out your suggestions and report back, Roger.

**Comment by RZulu54** [comment]
New version 4 should fix this.
